# Generated by Django 5.2.11 on 2026-02-18 21:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoveLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beloved_name', models.CharField(max_length=120)),
                ('beloved_nickname', models.CharField(blank=True, max_length=120)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('relationship_status', models.CharField(blank=True, choices=[('ficando', 'ficando'), ('namorando', 'namorando'), ('noivos', 'noivos'), ('casados', 'casados'), ('apaixonados', 'apaixonados'), ('outro', 'outro')], max_length=20)),
                ('relationship_custom', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('romantico', 'romântico'), ('intenso', 'intenso'), ('fofo', 'fofo'), ('divertido', 'divertido')], default='romantico', max_length=20)),
                ('music_url', models.URLField(blank=True)),
                ('music_provider', models.CharField(choices=[('youtube', 'YouTube'), ('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('deezer', 'Deezer'), ('amazon_music', 'Amazon Music'), ('unknown', 'Outro')], default='unknown', max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('3.99'), max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LovePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='letters/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='letters.loveletter')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('mercado_pago', 'Mercado Pago'), ('stripe', 'Stripe')], max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('3.99'), max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='letters.loveletter')),
            ],
        ),
    ]
