# Generated by Django 5.2.11 on 2026-02-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_loveletter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovephoto',
            name='display_mode',
            field=models.CharField(choices=[('contain', 'Ajustar'), ('cover', 'Preencher')], default='contain', max_length=10),
        ),
    ]
